export default function ExplainScreen({ recommendation, explanation, onBack, onBook, onRetake }) {
  const name = recommendation?.recommendedPackage?.name || 'this package';

  const sections = parseExplanation(explanation);

  return (
    <div className="flex flex-col min-h-dvh bg-white">
      {/* Header */}
      <div className="px-5 pt-12 pb-6">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm text-tc-green font-medium mb-6"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M19 12H5M12 5l-7 7 7 7"/>
          </svg>
          Back to recommendation
        </button>
        <div className="flex items-center gap-2 mb-2">
          <span className="text-lg">✨</span>
          <p className="text-xs font-semibold tracking-widest text-tc-green uppercase">AI explanation</p>
        </div>
        <h1 className="text-xl font-bold text-gray-900 leading-snug">
          Why {name}?
        </h1>
      </div>

      {/* Explanation body */}
      <div className="flex-1 px-5 pb-10 overflow-y-auto space-y-4">
        {sections.length > 0 ? (
          sections.map((section, i) => (
            <div key={i} className="bg-tc-green-bg rounded-2xl p-5">
              {section.heading && (
                <p className="text-xs font-bold tracking-wider text-tc-green uppercase mb-2">
                  {section.heading}
                </p>
              )}
              <p className="text-sm text-gray-700 leading-relaxed">{section.body}</p>
            </div>
          ))
        ) : (
          <div className="bg-tc-green-bg rounded-2xl p-5">
            <p className="text-sm text-gray-700 leading-relaxed">{explanation}</p>
          </div>
        )}

        <p className="text-xs text-gray-400 text-center mt-2 leading-relaxed px-4">
          This explanation is generated by AI based on your answers. It is not medical advice.
        </p>
      </div>

      {/* CTAs */}
      <div className="px-5 pb-10 space-y-3">
        <button
          className="w-full bg-tc-green text-white font-semibold text-base py-4 rounded-2xl active:bg-tc-green-dark transition-colors"
          onClick={onBook}
        >
          Book This Package
        </button>
        <button
          onClick={onRetake}
          className="w-full text-sm text-gray-400 py-2 hover:text-gray-600 transition-colors"
        >
          Retake questionnaire
        </button>
      </div>
    </div>
  );
}

// Splits LLM response into heading + body sections based on **bold** markdown headings
function parseExplanation(text) {
  if (!text) return [];

  const sections = [];
  const lines    = text.split('\n');
  let current    = null;

  for (const line of lines) {
    const headingMatch = line.match(/^\*\*(.+?)\*\*\s*$/);
    if (headingMatch) {
      if (current) sections.push(current);
      current = { heading: headingMatch[1], body: '' };
    } else if (line.trim()) {
      if (!current) current = { heading: null, body: '' };
      current.body += (current.body ? ' ' : '') + line.trim();
    }
  }

  if (current) sections.push(current);
  return sections;
}
